/*
 * Copyright (C) 2026 Franklin D. Amador
 *
 * This software is dual-licensed under the terms of the GPL v2.0 and
 * a commercial license. You may choose to use this software under either
 * license.
 *
 * See the LICENSE files in the project root for full license text.
 */

package embedded

import (
	"bytes"
	"fmt"
	"github.com/apiarytech/beedance/code"
	"github.com/apiarytech/beedance/compiler"
	"github.com/apiarytech/beedance/object"
	"github.com/apiarytech/beedance/vm"
	"io"
	"math"
	"strconv"
	"strings"
)

const goFileTemplate = `/*
 * Auto-generated by beedance.
 *
 * This is a self-contained Go program that embeds the beedance VM
 * and the bytecode for a specific IEC 61131-3 application.
 */

package main

import (
	"github.com/apiarytech/beedance/compiler"
	"github.com/apiarytech/beedance/object"
	"github.com/apiarytech/beedance/vm"
	"fmt"
	"time"
)

var generatedInstructions = %s

var generatedConstants []object.Object

// time is used only by TIME, DATE, TOD and DT constants.
var _ = time.Duration(0)

func init() {
%s
}

func main() {
	bytecode := &compiler.Bytecode{
		Instructions: generatedInstructions,
		Constants:    generatedConstants,
	}

	// Globals are sized to what the bytecode uses: the default of
	// vm.GlobalsSize slots does not fit in a microcontroller's RAM.
	machine := vm.New(bytecode, vm.WithGlobalsSize(%d))
	err := machine.Run()
	if err != nil {
		fmt.Printf("VM execution failed: %%s\n", err)
		return
	}

	// You can optionally inspect the final result on the stack.
	// lastPopped := machine.LastPoppedStackElem()
	// fmt.Println("Result:", lastPopped.Inspect())
}
`

// GenerateEmbeddedGo creates a self-contained Go program that includes the VM
// and the provided bytecode, writing it to the given writer.
func GenerateEmbeddedGo(writer io.Writer, bytecode *compiler.Bytecode) error {
	instructionsStr := instructionsToGoLiteral(bytecode.Instructions)
	constantsStr, err := constantsToGoLiterals(bytecode.Constants)
	if err != nil {
		return fmt.Errorf("failed to generate Go literals for constants: %w", err)
	}

	source := fmt.Sprintf(goFileTemplate, instructionsStr, constantsStr, vm.GlobalsNeeded(bytecode))
	_, err = writer.Write([]byte(source))
	return err
}

// instructionsToGoLiteral converts a byte slice of instructions into a Go byte slice literal string.
func instructionsToGoLiteral(ins code.Instructions) string {
	var out bytes.Buffer
	out.WriteString("[]byte{\n\t")
	for i, b := range ins {
		out.WriteString(fmt.Sprintf("0x%02x, ", b))
		if (i+1)%16 == 0 {
			out.WriteString("\n\t")
		}
	}
	out.WriteString("\n}")
	return out.String()
}

// constantsToGoLiterals generates the body of the `init()` function to populate the constants slice.
func constantsToGoLiterals(constants []object.Object) (string, error) {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("\tgeneratedConstants = make([]object.Object, %d)\n", len(constants)))

	for i, obj := range constants {
		literal, err := objectToGoLiteral(obj)
		if err != nil {
			return "", fmt.Errorf("error converting constant at index %d: %w", i, err)
		}
		out.WriteString(fmt.Sprintf("\tgeneratedConstants[%d] = %s\n", i, literal))
	}

	return out.String(), nil
}

// objectToGoLiteral converts a single object.Object into its Go literal representation.
func objectToGoLiteral(obj object.Object) (string, error) {
	if obj == nil {
		return "vm.Null", nil
	}

	switch o := obj.(type) {
	case *object.SInt:
		return fmt.Sprintf("&object.SInt{Value: %d}", o.Value), nil
	case *object.Int:
		return fmt.Sprintf("&object.Int{Value: %d}", o.Value), nil
	case *object.DInt:
		return fmt.Sprintf("&object.DInt{Value: %d}", o.Value), nil
	case *object.LInt:
		return fmt.Sprintf("&object.LInt{Value: %d}", o.Value), nil
	case *object.USInt:
		return fmt.Sprintf("&object.USInt{Value: %d}", o.Value), nil
	case *object.UInt:
		return fmt.Sprintf("&object.UInt{Value: %d}", o.Value), nil
	case *object.UDInt:
		return fmt.Sprintf("&object.UDInt{Value: %d}", o.Value), nil
	case *object.ULInt:
		return fmt.Sprintf("&object.ULInt{Value: %d}", o.Value), nil
	case *object.Byte:
		return fmt.Sprintf("&object.Byte{Value: %d}", o.Value), nil
	case *object.Word:
		return fmt.Sprintf("&object.Word{Value: %d}", o.Value), nil
	case *object.DWord:
		return fmt.Sprintf("&object.DWord{Value: %d}", o.Value), nil
	case *object.LWord:
		return fmt.Sprintf("&object.LWord{Value: %d}", o.Value), nil
	case *object.BitString:
		return fmt.Sprintf("&object.BitString{Value: %d, Width: %d}", o.Value, o.Width), nil
	case *object.Real:
		f, err := floatLiteral(o.Value)
		return fmt.Sprintf("&object.Real{Value: %s}", f), err
	case *object.LReal:
		f, err := floatLiteral(o.Value)
		return fmt.Sprintf("&object.LReal{Value: %s}", f), err
	case *object.String:
		return fmt.Sprintf("&object.String{Value: %q}", o.Value), nil
	case *object.WString:
		return fmt.Sprintf("&object.WString{Value: %q}", o.Value), nil
	case *object.Null:
		return "vm.Null", nil
	case *object.TimeOfDay:
		return fmt.Sprintf("&object.TimeOfDay{Value: time.Unix(0, %d).UTC()}", o.Value.UnixNano()), nil
	case *object.DateAndTime:
		return fmt.Sprintf("&object.DateAndTime{Value: time.Unix(0, %d).UTC()}", o.Value.UnixNano()), nil
	case *object.Array:
		var elems strings.Builder
		for i, e := range o.Elements {
			lit, err := objectToGoLiteral(e)
			if err != nil {
				return "", fmt.Errorf("array element %d: %w", i, err)
			}
			elems.WriteString("\n\t\t" + lit + ",")
		}
		return fmt.Sprintf("&object.Array{LowerBound: %d, Elements: []object.Object{%s\n\t}}", o.LowerBound, elems.String()), nil
	case *object.Boolean:
		if o.Value {
			return "vm.True", nil
		}
		return "vm.False", nil
	case *object.Time:
		return fmt.Sprintf("&object.Time{Value: time.Duration(%d)}", o.Value), nil
	case *object.Date:
		y, m, d := o.Value.Date()
		return fmt.Sprintf("&object.Date{Value: time.Date(%d, %d, %d, 0, 0, 0, 0, time.UTC)}", y, m, d), nil
	case *object.CompiledFunction:
		var paramNames, outputNames, outputIndices strings.Builder
		paramNames.WriteString("[]string{")
		for i, p := range o.ParameterNames {
			paramNames.WriteString(fmt.Sprintf("%q", p))
			if i < len(o.ParameterNames)-1 {
				paramNames.WriteString(", ")
			}
		}
		paramNames.WriteString("}")

		outputNames.WriteString("[]string{")
		for i, p := range o.OutputNames {
			outputNames.WriteString(fmt.Sprintf("%q", p))
			if i < len(o.OutputNames)-1 {
				outputNames.WriteString(", ")
			}
		}
		outputNames.WriteString("}")

		outputIndices.WriteString("[]int{")
		for i, p := range o.OutputIndices {
			outputIndices.WriteString(fmt.Sprintf("%d", p))
			if i < len(o.OutputIndices)-1 {
				outputIndices.WriteString(", ")
			}
		}
		outputIndices.WriteString("}")

		return fmt.Sprintf(
			"&object.CompiledFunction{Instructions: %s, NumLocals: %d, NumParameters: %d, ParameterNames: %s, OutputNames: %s, OutputIndices: %s}",
			instructionsToGoLiteral(o.Instructions),
			o.NumLocals,
			o.NumParameters,
			paramNames.String(),
			outputNames.String(),
			outputIndices.String(),
		), nil
	default:
		return "", fmt.Errorf("unsupported object type for Go literal generation: %s", obj.Type())
	}
}

// floatLiteral is v as a Go literal that reads back exactly.
func floatLiteral(v float64) (string, error) {
	if math.IsInf(v, 0) || math.IsNaN(v) {
		return "", fmt.Errorf("constant %v is not finite", v)
	}
	s := strconv.FormatFloat(v, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eEn") {
		s += ".0"
	}
	return s, nil
}
