/*
 * Copyright (C) 2026 Franklin D. Amador
 *
 * This software is dual-licensed under the terms of the GPL v2.0 and
 * a commercial license. You may choose to use this software under either
 * license.
 *
 * See the LICENSE files in the project root for full license text.
 */

package embedded

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/apiarytech/beedance/compiler"
	"github.com/apiarytech/beedance/object"
	"github.com/apiarytech/beedance/vm"
)

// ProgramOptions configures GenerateEmbeddedProgram.
type ProgramOptions struct {
	// Package of the generated file; default "main", with a main function.
	// Any other package gets Run and no main, for firmware of its own.
	Package string
	// Interval between the starts of scans; default 100 ms.
	Interval time.Duration
	// Scans bounds the scans main runs; 0 runs for ever.
	Scans int
}

// GenerateEmbeddedProgram writes Go that runs a compiled PROGRAM
// (compiler.CompileProgramUnit) as a PLC does: its initialization once, then
// its body scan by scan, Interval apart, the standard timers on the device's
// clock. The bytecode and its constants are Go literals, so nothing is
// compiled on the device: build it with TinyGo for a microcontroller.
//
// Run(scans, onScan) is the scan loop. onScan, which may be nil, is called
// after each scan with the VM, whose I/O image (VM.IO) holds the located
// variables: the place to read the pins into %I before the next scan and
// drive them from %Q.
func GenerateEmbeddedProgram(w io.Writer, prog *compiler.CompiledProgram, o ProgramOptions) error {
	if prog == nil || prog.InitBytecode == nil || prog.CyclicBytecode == nil {
		return fmt.Errorf("a compiled program with initialization and cyclic bytecode is needed")
	}
	if o.Package == "" {
		o.Package = "main"
	}
	if o.Interval <= 0 {
		o.Interval = 100 * time.Millisecond
	}
	initConsts, err := constantsTo("initConstants", prog.InitBytecode.Constants)
	if err != nil {
		return fmt.Errorf("initialization constants: %w", err)
	}
	scanConsts, err := constantsTo("scanConstants", prog.CyclicBytecode.Constants)
	if err != nil {
		return fmt.Errorf("cyclic constants: %w", err)
	}
	globals := max(vm.GlobalsNeeded(prog.InitBytecode), vm.GlobalsNeeded(prog.CyclicBytecode))
	main := ""
	if o.Package == "main" {
		main = fmt.Sprintf(programMain, o.Scans)
	}
	_, err = fmt.Fprintf(w, programTemplate, o.Package,
		instructionsToGoLiteral(prog.InitBytecode.Instructions), instructionsToGoLiteral(prog.CyclicBytecode.Instructions),
		initConsts, scanConsts, int64(o.Interval), globals, main)
	return err
}

// constantsTo is constantsToGoLiterals for a slice called name.
func constantsTo(name string, constants []object.Object) (string, error) {
	s, err := constantsToGoLiterals(constants)
	return strings.ReplaceAll(s, "generatedConstants", name), err
}

const programTemplate = `// Code generated by beedance (embedded.GenerateEmbeddedProgram). DO NOT EDIT.

package %s

import (
	"time"

	"github.com/apiarytech/beedance/compiler"
	"github.com/apiarytech/beedance/object"
	"github.com/apiarytech/beedance/stdlib" // the built-in functions, and the clock
	"github.com/apiarytech/beedance/vm"
)

var initInstructions = %s

var scanInstructions = %s

var initConstants, scanConstants []object.Object

func init() {
%s
%s
}

// Interval is the time between the starts of scans.
const Interval = time.Duration(%d)

// Run runs the program: its initialization, then scans Interval apart,
// scans of them (0: for ever). onScan, if not nil, is called after each
// scan with the VM, whose IO() holds the located variables by address.
// It returns the runtime error that stopped the program.
func Run(scans int, onScan func(machine *vm.VM)) error {
	object.FinalizeBuiltins()
	start := time.Now()
	clock := func() time.Duration { return time.Since(start) }
	globals := make([]object.Object, %d)
	initVM := vm.NewWithGlobalsStore(&compiler.Bytecode{Instructions: initInstructions, Constants: initConstants}, globals)
	scanVM := vm.NewWithGlobalsStore(&compiler.Bytecode{Instructions: scanInstructions, Constants: scanConstants}, globals)
	for idx, b := range stdlib.ClockBuiltins(clock) {
		initVM.SetBuiltin(idx, b)
		scanVM.SetBuiltin(idx, b)
	}
	if err := initVM.Run(); err != nil {
		return err
	}
	for addr, v := range initVM.IO() {
		scanVM.IO()[addr] = v
	}
	next := time.Now()
	for n := 0; scans == 0 || n < scans; n++ {
		scanVM.Reset()
		if err := scanVM.Run(); err != nil {
			return err
		}
		if onScan != nil {
			onScan(scanVM)
		}
		next = next.Add(Interval)
		if wait := time.Until(next); wait > 0 {
			time.Sleep(wait)
		} else {
			next = time.Now() // overrun: start the next scan now
		}
	}
	return nil
}
%s`

const programMain = `
func main() {
	if err := Run(%d, nil); err != nil {
		println("program stopped:", err.Error())
		return
	}
	println("program done")
}
`
