/*
 * Copyright (C) 2026 Franklin D. Amador
 *
 * This software is dual-licensed under the terms of the GPL v2.0 and
 * a commercial license. You may choose to use this software under either
 * license.
 *
 * See the LICENSE files in the project root for full license text.
 */

package stdlib

const (
	BuiltinAbs              = iota // ABS
	BuiltinAcos                    // ACOS
	BuiltinAdd                     // ADD
	BuiltinAnd                     // AND
	BuiltinAnyIntToAnyReal         // ANY_INT_TO_ANY_REAL
	BuiltinAnyIntToBcd             // ANY_INT_TO_BCD
	BuiltinAnyIntToBool            // ANY_INT_TO_BOOL
	BuiltinAnyIntToByte            // ANY_INT_TO_BYTE
	BuiltinAnyIntToDate            // ANY_INT_TO_DATE
	BuiltinAnyIntToDint            // ANY_INT_TO_DINT
	BuiltinAnyIntToDt              // ANY_INT_TO_DT
	BuiltinAnyIntToDword           // ANY_INT_TO_DWORD
	BuiltinAnyIntToInt             // ANY_INT_TO_INT
	BuiltinAnyIntToLint            // ANY_INT_TO_LINT
	BuiltinAnyIntToLreal           // ANY_INT_TO_LREAL
	BuiltinAnyIntToLword           // ANY_INT_TO_LWORD
	BuiltinAnyIntToReal            // ANY_INT_TO_REAL
	BuiltinAnyIntToSint            // ANY_INT_TO_SINT
	BuiltinAnyIntToString          // ANY_INT_TO_STRING
	BuiltinAnyIntToTime            // ANY_INT_TO_TIME
	BuiltinAnyIntToTod             // ANY_INT_TO_TOD
	BuiltinAnyIntToUdint           // ANY_INT_TO_UDINT
	BuiltinAnyIntToUint            // ANY_INT_TO_UINT
	BuiltinAnyIntToUlint           // ANY_INT_TO_ULINT
	BuiltinAnyIntToUsint           // ANY_INT_TO_USINT
	BuiltinAnyIntToWord            // ANY_INT_TO_WORD
	BuiltinAnyIntToWstring         // ANY_INT_TO_WSTRING
	BuiltinAnyRealToAnyInt         // ANY_REAL_TO_ANY_INT
	BuiltinAnyRealToBcd            // ANY_REAL_TO_BCD
	BuiltinAnyRealToBool           // ANY_REAL_TO_BOOL
	BuiltinAnyRealToByte           // ANY_REAL_TO_BYTE
	BuiltinAnyRealToDate           // ANY_REAL_TO_DATE
	BuiltinAnyRealToDint           // ANY_REAL_TO_DINT
	BuiltinAnyRealToDt             // ANY_REAL_TO_DT
	BuiltinAnyRealToDword          // ANY_REAL_TO_DWORD
	BuiltinAnyRealToInt            // ANY_REAL_TO_INT
	BuiltinAnyRealToLint           // ANY_REAL_TO_LINT
	BuiltinAnyRealToLreal          // ANY_REAL_TO_LREAL
	BuiltinAnyRealToLword          // ANY_REAL_TO_LWORD
	BuiltinAnyRealToReal           // ANY_REAL_TO_REAL
	BuiltinAnyRealToSint           // ANY_REAL_TO_SINT
	BuiltinAnyRealToString         // ANY_REAL_TO_STRING
	BuiltinAnyRealToTime           // ANY_REAL_TO_TIME
	BuiltinAnyRealToTod            // ANY_REAL_TO_TOD
	BuiltinAnyRealToUdint          // ANY_REAL_TO_UDINT
	BuiltinAnyRealToUint           // ANY_REAL_TO_UINT
	BuiltinAnyRealToUlint          // ANY_REAL_TO_ULINT
	BuiltinAnyRealToUsint          // ANY_REAL_TO_USINT
	BuiltinAnyRealToWord           // ANY_REAL_TO_WORD
	BuiltinAnyRealToWstring        // ANY_REAL_TO_WSTRING
	BuiltinAsin                    // ASIN
	BuiltinAtan                    // ATAN
	BuiltinAtan2                   // ATAN2
	BuiltinBcdToAnyInt             // BCD_TO_ANY_INT
	BuiltinBcdToAnyReal            // BCD_TO_ANY_REAL
	BuiltinBcdToBool               // BCD_TO_BOOL
	BuiltinBcdToByte               // BCD_TO_BYTE
	BuiltinBcdToDate               // BCD_TO_DATE
	BuiltinBcdToDint               // BCD_TO_DINT
	BuiltinBcdToDt                 // BCD_TO_DT
	BuiltinBcdToDword              // BCD_TO_DWORD
	BuiltinBcdToInt                // BCD_TO_INT
	BuiltinBcdToLint               // BCD_TO_LINT
	BuiltinBcdToLreal              // BCD_TO_LREAL
	BuiltinBcdToLword              // BCD_TO_LWORD
	BuiltinBcdToReal               // BCD_TO_REAL
	BuiltinBcdToSint               // BCD_TO_SINT
	BuiltinBcdToString             // BCD_TO_STRING
	BuiltinBcdToTime               // BCD_TO_TIME
	BuiltinBcdToTod                // BCD_TO_TOD
	BuiltinBcdToUdint              // BCD_TO_UDINT
	BuiltinBcdToUint               // BCD_TO_UINT
	BuiltinBcdToUlint              // BCD_TO_ULINT
	BuiltinBcdToUsint              // BCD_TO_USINT
	BuiltinBcdToWord               // BCD_TO_WORD
	BuiltinBcdToWstring            // BCD_TO_WSTRING
	BuiltinBoolToAnyInt            // BOOL_TO_ANY_INT
	BuiltinBoolToAnyReal           // BOOL_TO_ANY_REAL
	BuiltinBoolToBcd               // BOOL_TO_BCD
	BuiltinBoolToByte              // BOOL_TO_BYTE
	BuiltinBoolToDate              // BOOL_TO_DATE
	BuiltinBoolToDint              // BOOL_TO_DINT
	BuiltinBoolToDt                // BOOL_TO_DT
	BuiltinBoolToDword             // BOOL_TO_DWORD
	BuiltinBoolToInt               // BOOL_TO_INT
	BuiltinBoolToLint              // BOOL_TO_LINT
	BuiltinBoolToLreal             // BOOL_TO_LREAL
	BuiltinBoolToLword             // BOOL_TO_LWORD
	BuiltinBoolToReal              // BOOL_TO_REAL
	BuiltinBoolToSint              // BOOL_TO_SINT
	BuiltinBoolToString            // BOOL_TO_STRING
	BuiltinBoolToTime              // BOOL_TO_TIME
	BuiltinBoolToTod               // BOOL_TO_TOD
	BuiltinBoolToUdint             // BOOL_TO_UDINT
	BuiltinBoolToUint              // BOOL_TO_UINT
	BuiltinBoolToUlint             // BOOL_TO_ULINT
	BuiltinBoolToUsint             // BOOL_TO_USINT
	BuiltinBoolToWord              // BOOL_TO_WORD
	BuiltinBoolToWstring           // BOOL_TO_WSTRING
	BuiltinByteToAnyInt            // BYTE_TO_ANY_INT
	BuiltinByteToAnyReal           // BYTE_TO_ANY_REAL
	BuiltinByteToBcd               // BYTE_TO_BCD
	BuiltinByteToBool              // BYTE_TO_BOOL
	BuiltinByteToDate              // BYTE_TO_DATE
	BuiltinByteToDint              // BYTE_TO_DINT
	BuiltinByteToDt                // BYTE_TO_DT
	BuiltinByteToDword             // BYTE_TO_DWORD
	BuiltinByteToInt               // BYTE_TO_INT
	BuiltinByteToLint              // BYTE_TO_LINT
	BuiltinByteToLreal             // BYTE_TO_LREAL
	BuiltinByteToLword             // BYTE_TO_LWORD
	BuiltinByteToReal              // BYTE_TO_REAL
	BuiltinByteToSint              // BYTE_TO_SINT
	BuiltinByteToString            // BYTE_TO_STRING
	BuiltinByteToTime              // BYTE_TO_TIME
	BuiltinByteToTod               // BYTE_TO_TOD
	BuiltinByteToUdint             // BYTE_TO_UDINT
	BuiltinByteToUint              // BYTE_TO_UINT
	BuiltinByteToUlint             // BYTE_TO_ULINT
	BuiltinByteToUsint             // BYTE_TO_USINT
	BuiltinByteToWord              // BYTE_TO_WORD
	BuiltinByteToWstring           // BYTE_TO_WSTRING
	BuiltinConcat                  // CONCAT
	BuiltinCos                     // COS
	BuiltinDateToAnyInt            // DATE_TO_ANY_INT
	BuiltinDateToAnyReal           // DATE_TO_ANY_REAL
	BuiltinDateToBcd               // DATE_TO_BCD
	BuiltinDateToBool              // DATE_TO_BOOL
	BuiltinDateToByte              // DATE_TO_BYTE
	BuiltinDateToDint              // DATE_TO_DINT
	BuiltinDateToDt                // DATE_TO_DT
	BuiltinDateToDword             // DATE_TO_DWORD
	BuiltinDateToInt               // DATE_TO_INT
	BuiltinDateToLint              // DATE_TO_LINT
	BuiltinDateToLreal             // DATE_TO_LREAL
	BuiltinDateToLword             // DATE_TO_LWORD
	BuiltinDateToReal              // DATE_TO_REAL
	BuiltinDateToSint              // DATE_TO_SINT
	BuiltinDateToString            // DATE_TO_STRING
	BuiltinDateToTime              // DATE_TO_TIME
	BuiltinDateToTod               // DATE_TO_TOD
	BuiltinDateToUdint             // DATE_TO_UDINT
	BuiltinDateToUint              // DATE_TO_UINT
	BuiltinDateToUlint             // DATE_TO_ULINT
	BuiltinDateToUsint             // DATE_TO_USINT
	BuiltinDateToWord              // DATE_TO_WORD
	BuiltinDateToWstring           // DATE_TO_WSTRING
	BuiltinDelete                  // DELETE
	BuiltinDintToAnyInt            // DINT_TO_ANY_INT
	BuiltinDintToAnyReal           // DINT_TO_ANY_REAL
	BuiltinDintToBcd               // DINT_TO_BCD
	BuiltinDintToBool              // DINT_TO_BOOL
	BuiltinDintToByte              // DINT_TO_BYTE
	BuiltinDintToDate              // DINT_TO_DATE
	BuiltinDintToDt                // DINT_TO_DT
	BuiltinDintToDword             // DINT_TO_DWORD
	BuiltinDintToInt               // DINT_TO_INT
	BuiltinDintToLint              // DINT_TO_LINT
	BuiltinDintToLreal             // DINT_TO_LREAL
	BuiltinDintToLword             // DINT_TO_LWORD
	BuiltinDintToReal              // DINT_TO_REAL
	BuiltinDintToSint              // DINT_TO_SINT
	BuiltinDintToString            // DINT_TO_STRING
	BuiltinDintToTime              // DINT_TO_TIME
	BuiltinDintToTod               // DINT_TO_TOD
	BuiltinDintToUdint             // DINT_TO_UDINT
	BuiltinDintToUint              // DINT_TO_UINT
	BuiltinDintToUlint             // DINT_TO_ULINT
	BuiltinDintToUsint             // DINT_TO_USINT
	BuiltinDintToWord              // DINT_TO_WORD
	BuiltinDintToWstring           // DINT_TO_WSTRING
	BuiltinDiv                     // DIV
	BuiltinDwordToAnyInt           // DWORD_TO_ANY_INT
	BuiltinDwordToAnyReal          // DWORD_TO_ANY_REAL
	BuiltinDwordToBcd              // DWORD_TO_BCD
	BuiltinDwordToBool             // DWORD_TO_BOOL
	BuiltinDwordToByte             // DWORD_TO_BYTE
	BuiltinDwordToDate             // DWORD_TO_DATE
	BuiltinDwordToDint             // DWORD_TO_DINT
	BuiltinDwordToDt               // DWORD_TO_DT
	BuiltinDwordToInt              // DWORD_TO_INT
	BuiltinDwordToLint             // DWORD_TO_LINT
	BuiltinDwordToLreal            // DWORD_TO_LREAL
	BuiltinDwordToLword            // DWORD_TO_LWORD
	BuiltinDwordToReal             // DWORD_TO_REAL
	BuiltinDwordToSint             // DWORD_TO_SINT
	BuiltinDwordToString           // DWORD_TO_STRING
	BuiltinDwordToTime             // DWORD_TO_TIME
	BuiltinDwordToTod              // DWORD_TO_TOD
	BuiltinDwordToUdint            // DWORD_TO_UDINT
	BuiltinDwordToUint             // DWORD_TO_UINT
	BuiltinDwordToUlint            // DWORD_TO_ULINT
	BuiltinDwordToUsint            // DWORD_TO_USINT
	BuiltinDwordToWord             // DWORD_TO_WORD
	BuiltinDwordToWstring          // DWORD_TO_WSTRING
	BuiltinDtToAnyInt              // DT_TO_ANY_INT
	BuiltinDtToAnyReal             // DT_TO_ANY_REAL
	BuiltinDtToBcd                 // DT_TO_BCD
	BuiltinDtToBool                // DT_TO_BOOL
	BuiltinDtToByte                // DT_TO_BYTE
	BuiltinDtToDate                // DT_TO_DATE
	BuiltinDtToDint                // DT_TO_DINT
	BuiltinDtToDword               // DT_TO_DWORD
	BuiltinDtToInt                 // DT_TO_INT
	BuiltinDtToLint                // DT_TO_LINT
	BuiltinDtToLreal               // DT_TO_LREAL
	BuiltinDtToLword               // DT_TO_LWORD
	BuiltinDtToReal                // DT_TO_REAL
	BuiltinDtToSint                // DT_TO_SINT
	BuiltinDtToString              // DT_TO_STRING
	BuiltinDtToTime                // DT_TO_TIME
	BuiltinDtToTod                 // DT_TO_TOD
	BuiltinDtToUdint               // DT_TO_UDINT
	BuiltinDtToUint                // DT_TO_UINT
	BuiltinDtToUlint               // DT_TO_ULINT
	BuiltinDtToUsint               // DT_TO_USINT
	BuiltinDtToWord                // DT_TO_WORD
	BuiltinDtToWstring             // DT_TO_WSTRING
	BuiltinEq                      // EQ
	BuiltinExp                     // EXP
	BuiltinExpt                    // EXPT
	BuiltinFind                    // FIND
	BuiltinFirst                   // FIRST
	BuiltinGe                      // GE
	BuiltinGt                      // GT
	BuiltinGreat                   // GREAT
	BuiltinInsert                  // INSERT
	BuiltinIntToAnyInt             // INT_TO_ANY_INT
	BuiltinIntToAnyReal            // INT_TO_ANY_REAL
	BuiltinIntToBcd                // INT_TO_BCD
	BuiltinIntToBool               // INT_TO_BOOL
	BuiltinIntToByte               // INT_TO_BYTE
	BuiltinIntToDate               // INT_TO_DATE
	BuiltinIntToDint               // INT_TO_DINT
	BuiltinIntToDt                 // INT_TO_DT
	BuiltinIntToDword              // INT_TO_DWORD
	BuiltinIntToLint               // INT_TO_LINT
	BuiltinIntToLreal              // INT_TO_LREAL
	BuiltinIntToLword              // INT_TO_LWORD
	BuiltinIntToReal               // INT_TO_REAL
	BuiltinIntToSint               // INT_TO_SINT
	BuiltinIntToString             // INT_TO_STRING
	BuiltinIntToTime               // INT_TO_TIME
	BuiltinIntToTod                // INT_TO_TOD
	BuiltinIntToUdint              // INT_TO_UDINT
	BuiltinIntToUint               // INT_TO_UINT
	BuiltinIntToUlint              // INT_TO_ULINT
	BuiltinIntToUsint              // INT_TO_USINT
	BuiltinIntToWord               // INT_TO_WORD
	BuiltinIntToWstring            // INT_TO_WSTRING
	BuiltinLast                    // LAST
	BuiltinLe                      // LE
	BuiltinLeft                    // LEFT
	BuiltinLen                     // LEN
	BuiltinLimit                   // LIMIT
	BuiltinLintToAnyInt            // LINT_TO_ANY_INT
	BuiltinLintToAnyReal           // LINT_TO_ANY_REAL
	BuiltinLintToBcd               // LINT_TO_BCD
	BuiltinLintToBool              // LINT_TO_BOOL
	BuiltinLintToByte              // LINT_TO_BYTE
	BuiltinLintToDate              // LINT_TO_DATE
	BuiltinLintToDint              // LINT_TO_DINT
	BuiltinLintToDt                // LINT_TO_DT
	BuiltinLintToDword             // LINT_TO_DWORD
	BuiltinLintToInt               // LINT_TO_INT
	BuiltinLintToLreal             // LINT_TO_LREAL
	BuiltinLintToLword             // LINT_TO_LWORD
	BuiltinLintToReal              // LINT_TO_REAL
	BuiltinLintToSint              // LINT_TO_SINT
	BuiltinLintToString            // LINT_TO_STRING
	BuiltinLintToTime              // LINT_TO_TIME
	BuiltinLintToTod               // LINT_TO_TOD
	BuiltinLintToUdint             // LINT_TO_UDINT
	BuiltinLintToUint              // LINT_TO_UINT
	BuiltinLintToUlint             // LINT_TO_ULINT
	BuiltinLintToUsint             // LINT_TO_USINT
	BuiltinLintToWord              // LINT_TO_WORD
	BuiltinLintToWstring           // LINT_TO_WSTRING
	BuiltinLn                      // LN
	BuiltinLog                     // LOG
	BuiltinLowerBound              // LOWER_BOUND
	BuiltinLrealToAnyInt           // LREAL_TO_ANY_INT
	BuiltinLrealToAnyReal          // LREAL_TO_ANY_REAL
	BuiltinLrealToBcd              // LREAL_TO_BCD
	BuiltinLrealToBool             // LREAL_TO_BOOL
	BuiltinLrealToByte             // LREAL_TO_BYTE
	BuiltinLrealToDate             // LREAL_TO_DATE
	BuiltinLrealToDint             // LREAL_TO_DINT
	BuiltinLrealToDt               // LREAL_TO_DT
	BuiltinLrealToDword            // LREAL_TO_DWORD
	BuiltinLrealToInt              // LREAL_TO_INT
	BuiltinLrealToLint             // LREAL_TO_LINT
	BuiltinLrealToLword            // LREAL_TO_LWORD
	BuiltinLrealToReal             // LREAL_TO_REAL
	BuiltinLrealToSint             // LREAL_TO_SINT
	BuiltinLrealToString           // LREAL_TO_STRING
	BuiltinLrealToTime             // LREAL_TO_TIME
	BuiltinLrealToTod              // LREAL_TO_TOD
	BuiltinLrealToUdint            // LREAL_TO_UDINT
	BuiltinLrealToUint             // LREAL_TO_UINT
	BuiltinLrealToUlint            // LREAL_TO_ULINT
	BuiltinLrealToUsint            // LREAL_TO_USINT
	BuiltinLrealToWord             // LREAL_TO_WORD
	BuiltinLrealToWstring          // LREAL_TO_WSTRING
	BuiltinLt                      // LT
	BuiltinLwordToAnyInt           // LWORD_TO_ANY_INT
	BuiltinLwordToAnyReal          // LWORD_TO_ANY_REAL
	BuiltinLwordToBcd              // LWORD_TO_BCD
	BuiltinLwordToBool             // LWORD_TO_BOOL
	BuiltinLwordToByte             // LWORD_TO_BYTE
	BuiltinLwordToDate             // LWORD_TO_DATE
	BuiltinLwordToDint             // LWORD_TO_DINT
	BuiltinLwordToDt               // LWORD_TO_DT
	BuiltinLwordToDword            // LWORD_TO_DWORD
	BuiltinLwordToInt              // LWORD_TO_INT
	BuiltinLwordToLint             // LWORD_TO_LINT
	BuiltinLwordToLreal            // LWORD_TO_LREAL
	BuiltinLwordToReal             // LWORD_TO_REAL
	BuiltinLwordToSint             // LWORD_TO_SINT
	BuiltinLwordToString           // LWORD_TO_STRING
	BuiltinLwordToTime             // LWORD_TO_TIME
	BuiltinLwordToTod              // LWORD_TO_TOD
	BuiltinLwordToUdint            // LWORD_TO_UDINT
	BuiltinLwordToUint             // LWORD_TO_UINT
	BuiltinLwordToUlint            // LWORD_TO_ULINT
	BuiltinLwordToUsint            // LWORD_TO_USINT
	BuiltinLwordToWord             // LWORD_TO_WORD
	BuiltinLwordToWstring          // LWORD_TO_WSTRING
	BuiltinMax                     // MAX
	BuiltinMid                     // MID
	BuiltinMin                     // MIN
	BuiltinMod                     // MOD
	BuiltinMove                    // MOVE
	BuiltinMul                     // MUL
	BuiltinMux                     // MUX
	BuiltinNand                    // NAND
	BuiltinNe                      // NE
	BuiltinNor                     // NOR
	BuiltinOr                      // OR
	BuiltinPop                     // POP
	BuiltinPush                    // PUSH
	BuiltinPuts                    // PUTS
	BuiltinRealToAnyInt            // REAL_TO_ANY_INT
	BuiltinRealToAnyReal           // REAL_TO_ANY_REAL
	BuiltinRealToBcd               // REAL_TO_BCD
	BuiltinRealToBool              // REAL_TO_BOOL
	BuiltinRealToByte              // REAL_TO_BYTE
	BuiltinRealToDate              // REAL_TO_DATE
	BuiltinRealToDint              // REAL_TO_DINT
	BuiltinRealToDt                // REAL_TO_DT
	BuiltinRealToDword             // REAL_TO_DWORD
	BuiltinRealToInt               // REAL_TO_INT
	BuiltinRealToLint              // REAL_TO_LINT
	BuiltinRealToLreal             // REAL_TO_LREAL
	BuiltinRealToLword             // REAL_TO_LWORD
	BuiltinRealToSint              // REAL_TO_SINT
	BuiltinRealToString            // REAL_TO_STRING
	BuiltinRealToTime              // REAL_TO_TIME
	BuiltinRealToTod               // REAL_TO_TOD
	BuiltinRealToUdint             // REAL_TO_UDINT
	BuiltinRealToUint              // REAL_TO_UINT
	BuiltinRealToUlint             // REAL_TO_ULINT
	BuiltinRealToUsint             // REAL_TO_USINT
	BuiltinRealToWord              // REAL_TO_WORD
	BuiltinRealToWstring           // REAL_TO_WSTRING
	BuiltinReplace                 // REPLACE
	BuiltinRest                    // REST
	BuiltinRight                   // RIGHT
	BuiltinRol                     // ROL
	BuiltinRor                     // ROR
	BuiltinRound                   // ROUND
	BuiltinSel                     // SEL
	BuiltinShl                     // SHL
	BuiltinShr                     // SHR
	BuiltinSin                     // SIN
	BuiltinSintToAnyInt            // SINT_TO_ANY_INT
	BuiltinSintToAnyReal           // SINT_TO_ANY_REAL
	BuiltinSintToBcd               // SINT_TO_BCD
	BuiltinSintToBool              // SINT_TO_BOOL
	BuiltinSintToByte              // SINT_TO_BYTE
	BuiltinSintToDate              // SINT_TO_DATE
	BuiltinSintToDint              // SINT_TO_DINT
	BuiltinSintToDt                // SINT_TO_DT
	BuiltinSintToDword             // SINT_TO_DWORD
	BuiltinSintToInt               // SINT_TO_INT
	BuiltinSintToLint              // SINT_TO_LINT
	BuiltinSintToLreal             // SINT_TO_LREAL
	BuiltinSintToLword             // SINT_TO_LWORD
	BuiltinSintToReal              // SINT_TO_REAL
	BuiltinSintToString            // SINT_TO_STRING
	BuiltinSintToTime              // SINT_TO_TIME
	BuiltinSintToTod               // SINT_TO_TOD
	BuiltinSintToUdint             // SINT_TO_UDINT
	BuiltinSintToUint              // SINT_TO_UINT
	BuiltinSintToUlint             // SINT_TO_ULINT
	BuiltinSintToUsint             // SINT_TO_USINT
	BuiltinSintToWord              // SINT_TO_WORD
	BuiltinSintToWstring           // SINT_TO_WSTRING
	BuiltinSqrt                    // SQRT
	BuiltinStringToAnyInt          // STRING_TO_ANY_INT
	BuiltinStringToAnyReal         // STRING_TO_ANY_REAL
	BuiltinStringToBcd             // STRING_TO_BCD
	BuiltinStringToBool            // STRING_TO_BOOL
	BuiltinStringToByte            // STRING_TO_BYTE
	BuiltinStringToDate            // STRING_TO_DATE
	BuiltinStringToDint            // STRING_TO_DINT
	BuiltinStringToDt              // STRING_TO_DT
	BuiltinStringToDword           // STRING_TO_DWORD
	BuiltinStringToInt             // STRING_TO_INT
	BuiltinStringToLint            // STRING_TO_LINT
	BuiltinStringToLreal           // STRING_TO_LREAL
	BuiltinStringToLword           // STRING_TO_LWORD
	BuiltinStringToReal            // STRING_TO_REAL
	BuiltinStringToSint            // STRING_TO_SINT
	BuiltinStringToTime            // STRING_TO_TIME
	BuiltinStringToTod             // STRING_TO_TOD
	BuiltinStringToUdint           // STRING_TO_UDINT
	BuiltinStringToUint            // STRING_TO_UINT
	BuiltinStringToUlint           // STRING_TO_ULINT
	BuiltinStringToUsint           // STRING_TO_USINT
	BuiltinStringToWord            // STRING_TO_WORD
	BuiltinStringToWstring         // STRING_TO_WSTRING
	BuiltinSub                     // SUB
	BuiltinTan                     // TAN
	BuiltinTimeToAnyInt            // TIME_TO_ANY_INT
	BuiltinTimeToAnyReal           // TIME_TO_ANY_REAL
	BuiltinTimeToBcd               // TIME_TO_BCD
	BuiltinTimeToBool              // TIME_TO_BOOL
	BuiltinTimeToByte              // TIME_TO_BYTE
	BuiltinTimeToDate              // TIME_TO_DATE
	BuiltinTimeToDint              // TIME_TO_DINT
	BuiltinTimeToDt                // TIME_TO_DT
	BuiltinTimeToDword             // TIME_TO_DWORD
	BuiltinTimeToInt               // TIME_TO_INT
	BuiltinTimeToLint              // TIME_TO_LINT
	BuiltinTimeToLreal             // TIME_TO_LREAL
	BuiltinTimeToLword             // TIME_TO_LWORD
	BuiltinTimeToReal              // TIME_TO_REAL
	BuiltinTimeToSint              // TIME_TO_SINT
	BuiltinTimeToString            // TIME_TO_STRING
	BuiltinTimeToTod               // TIME_TO_TOD
	BuiltinTimeToUdint             // TIME_TO_UDINT
	BuiltinTimeToUint              // TIME_TO_UINT
	BuiltinTimeToUlint             // TIME_TO_ULINT
	BuiltinTimeToUsint             // TIME_TO_USINT
	BuiltinTimeToWord              // TIME_TO_WORD
	BuiltinTimeToWstring           // TIME_TO_WSTRING
	BuiltinTodToAnyInt             // TOD_TO_ANY_INT
	BuiltinTodToAnyReal            // TOD_TO_ANY_REAL
	BuiltinTodToBcd                // TOD_TO_BCD
	BuiltinTodToBool               // TOD_TO_BOOL
	BuiltinTodToByte               // TOD_TO_BYTE
	BuiltinTodToDate               // TOD_TO_DATE
	BuiltinTodToDint               // TOD_TO_DINT
	BuiltinTodToDt                 // TOD_TO_DT
	BuiltinTodToDword              // TOD_TO_DWORD
	BuiltinTodToInt                // TOD_TO_INT
	BuiltinTodToLint               // TOD_TO_LINT
	BuiltinTodToLreal              // TOD_TO_LREAL
	BuiltinTodToLword              // TOD_TO_LWORD
	BuiltinTodToReal               // TOD_TO_REAL
	BuiltinTodToSint               // TOD_TO_SINT
	BuiltinTodToString             // TOD_TO_STRING
	BuiltinTodToTime               // TOD_TO_TIME
	BuiltinTodToUdint              // TOD_TO_UDINT
	BuiltinTodToUint               // TOD_TO_UINT
	BuiltinTodToUlint              // TOD_TO_ULINT
	BuiltinTodToUsint              // TOD_TO_USINT
	BuiltinTodToWord               // TOD_TO_WORD
	BuiltinTodToWstring            // TOD_TO_WSTRING
	BuiltinTrunc                   // TRUNC
	BuiltinUdintToAnyInt           // UDINT_TO_ANY_INT
	BuiltinUdintToAnyReal          // UDINT_TO_ANY_REAL
	BuiltinUdintToBcd              // UDINT_TO_BCD
	BuiltinUdintToBool             // UDINT_TO_BOOL
	BuiltinUdintToByte             // UDINT_TO_BYTE
	BuiltinUdintToDate             // UDINT_TO_DATE
	BuiltinUdintToDint             // UDINT_TO_DINT
	BuiltinUdintToDt               // UDINT_TO_DT
	BuiltinUdintToDword            // UDINT_TO_DWORD
	BuiltinUdintToInt              // UDINT_TO_INT
	BuiltinUdintToLint             // UDINT_TO_LINT
	BuiltinUdintToLreal            // UDINT_TO_LREAL
	BuiltinUdintToLword            // UDINT_TO_LWORD
	BuiltinUdintToReal             // UDINT_TO_REAL
	BuiltinUdintToSint             // UDINT_TO_SINT
	BuiltinUdintToString           // UDINT_TO_STRING
	BuiltinUdintToTime             // UDINT_TO_TIME
	BuiltinUdintToTod              // UDINT_TO_TOD
	BuiltinUdintToUint             // UDINT_TO_UINT
	BuiltinUdintToUlint            // UDINT_TO_ULINT
	BuiltinUdintToUsint            // UDINT_TO_USINT
	BuiltinUdintToWord             // UDINT_TO_WORD
	BuiltinUdintToWstring          // UDINT_TO_WSTRING
	BuiltinUintToAnyInt            // UINT_TO_ANY_INT
	BuiltinUintToAnyReal           // UINT_TO_ANY_REAL
	BuiltinUintToBcd               // UINT_TO_BCD
	BuiltinUintToBool              // UINT_TO_BOOL
	BuiltinUintToByte              // UINT_TO_BYTE
	BuiltinUintToDate              // UINT_TO_DATE
	BuiltinUintToDint              // UINT_TO_DINT
	BuiltinUintToDt                // UINT_TO_DT
	BuiltinUintToDword             // UINT_TO_DWORD
	BuiltinUintToInt               // UINT_TO_INT
	BuiltinUintToLint              // UINT_TO_LINT
	BuiltinUintToLreal             // UINT_TO_LREAL
	BuiltinUintToLword             // UINT_TO_LWORD
	BuiltinUintToReal              // UINT_TO_REAL
	BuiltinUintToSint              // UINT_TO_SINT
	BuiltinUintToString            // UINT_TO_STRING
	BuiltinUintToTime              // UINT_TO_TIME
	BuiltinUintToTod               // UINT_TO_TOD
	BuiltinUintToUdint             // UINT_TO_UDINT
	BuiltinUintToUlint             // UINT_TO_ULINT
	BuiltinUintToUsint             // UINT_TO_USINT
	BuiltinUintToWord              // UINT_TO_WORD
	BuiltinUintToWstring           // UINT_TO_WSTRING
	BuiltinUlintToAnyInt           // ULINT_TO_ANY_INT
	BuiltinUlintToAnyReal          // ULINT_TO_ANY_REAL
	BuiltinUlintToBcd              // ULINT_TO_BCD
	BuiltinUlintToBool             // ULINT_TO_BOOL
	BuiltinUlintToByte             // ULINT_TO_BYTE
	BuiltinUlintToDate             // ULINT_TO_DATE
	BuiltinUlintToDint             // ULINT_TO_DINT
	BuiltinUlintToDt               // ULINT_TO_DT
	BuiltinUlintToDword            // ULINT_TO_DWORD
	BuiltinUlintToInt              // ULINT_TO_INT
	BuiltinUlintToLint             // ULINT_TO_LINT
	BuiltinUlintToLreal            // ULINT_TO_LREAL
	BuiltinUlintToLword            // ULINT_TO_LWORD
	BuiltinUlintToReal             // ULINT_TO_REAL
	BuiltinUlintToSint             // ULINT_TO_SINT
	BuiltinUlintToString           // ULINT_TO_STRING
	BuiltinUlintToTime             // ULINT_TO_TIME
	BuiltinUlintToTod              // ULINT_TO_TOD
	BuiltinUlintToUdint            // ULINT_TO_UDINT
	BuiltinUlintToUint             // ULINT_TO_UINT
	BuiltinUlintToUsint            // ULINT_TO_USINT
	BuiltinUlintToWord             // ULINT_TO_WORD
	BuiltinUlintToWstring          // ULINT_TO_WSTRING
	BuiltinUpperBound              // UPPER_BOUND
	BuiltinUsintToAnyInt           // USINT_TO_ANY_INT
	BuiltinUsintToAnyReal          // USINT_TO_ANY_REAL
	BuiltinUsintToBcd              // USINT_TO_BCD
	BuiltinUsintToBool             // USINT_TO_BOOL
	BuiltinUsintToByte             // USINT_TO_BYTE
	BuiltinUsintToDate             // USINT_TO_DATE
	BuiltinUsintToDint             // USINT_TO_DINT
	BuiltinUsintToDt               // USINT_TO_DT
	BuiltinUsintToDword            // USINT_TO_DWORD
	BuiltinUsintToInt              // USINT_TO_INT
	BuiltinUsintToLint             // USINT_TO_LINT
	BuiltinUsintToLreal            // USINT_TO_LREAL
	BuiltinUsintToLword            // USINT_TO_LWORD
	BuiltinUsintToReal             // USINT_TO_REAL
	BuiltinUsintToSint             // USINT_TO_SINT
	BuiltinUsintToString           // USINT_TO_STRING
	BuiltinUsintToTime             // USINT_TO_TIME
	BuiltinUsintToTod              // USINT_TO_TOD
	BuiltinUsintToUdint            // USINT_TO_UDINT
	BuiltinUsintToUint             // USINT_TO_UINT
	BuiltinUsintToUlint            // USINT_TO_ULINT
	BuiltinUsintToWord             // USINT_TO_WORD
	BuiltinUsintToWstring          // USINT_TO_WSTRING
	BuiltinWordToAnyInt            // WORD_TO_ANY_INT
	BuiltinWordToAnyReal           // WORD_TO_ANY_REAL
	BuiltinWordToBcd               // WORD_TO_BCD
	BuiltinWordToBool              // WORD_TO_BOOL
	BuiltinWordToByte              // WORD_TO_BYTE
	BuiltinWordToDate              // WORD_TO_DATE
	BuiltinWordToDint              // WORD_TO_DINT
	BuiltinWordToDt                // WORD_TO_DT
	BuiltinWordToDword             // WORD_TO_DWORD
	BuiltinWordToInt               // WORD_TO_INT
	BuiltinWordToLint              // WORD_TO_LINT
	BuiltinWordToLreal             // WORD_TO_LREAL
	BuiltinWordToLword             // WORD_TO_LWORD
	BuiltinWordToReal              // WORD_TO_REAL
	BuiltinWordToSint              // WORD_TO_SINT
	BuiltinWordToString            // WORD_TO_STRING
	BuiltinWordToTime              // WORD_TO_TIME
	BuiltinWordToTod               // WORD_TO_TOD
	BuiltinWordToUdint             // WORD_TO_UDINT
	BuiltinWordToUint              // WORD_TO_UINT
	BuiltinWordToUlint             // WORD_TO_ULINT
	BuiltinWordToUsint             // WORD_TO_USINT
	BuiltinWordToWstring           // WORD_TO_WSTRING
	BuiltinWstringToAnyInt         // WSTRING_TO_ANY_INT
	BuiltinWstringToAnyReal        // WSTRING_TO_ANY_REAL
	BuiltinWstringToBcd            // WSTRING_TO_BCD
	BuiltinWstringToBool           // WSTRING_TO_BOOL
	BuiltinWstringToByte           // WSTRING_TO_BYTE
	BuiltinWstringToDate           // WSTRING_TO_DATE
	BuiltinWstringToDint           // WSTRING_TO_DINT
	BuiltinWstringToDt             // WSTRING_TO_DT
	BuiltinWstringToDword          // WSTRING_TO_DWORD
	BuiltinWstringToInt            // WSTRING_TO_INT
	BuiltinWstringToLint           // WSTRING_TO_LINT
	BuiltinWstringToLreal          // WSTRING_TO_LREAL
	BuiltinWstringToLword          // WSTRING_TO_LWORD
	BuiltinWstringToReal           // WSTRING_TO_REAL
	BuiltinWstringToSint           // WSTRING_TO_SINT
	BuiltinWstringToString         // WSTRING_TO_STRING
	BuiltinWstringToTime           // WSTRING_TO_TIME
	BuiltinWstringToTod            // WSTRING_TO_TOD
	BuiltinWstringToUdint          // WSTRING_TO_UDINT
	BuiltinWstringToUint           // WSTRING_TO_UINT
	BuiltinWstringToUlint          // WSTRING_TO_ULINT
	BuiltinWstringToUsint          // WSTRING_TO_USINT
	BuiltinWstringToWord           // WSTRING_TO_WORD
	BuiltinXor                     // XOR
)
