/*
 * Copyright (C) 2026 Franklin D. Amador
 *
 * This software is dual-licensed under the terms of the GPL v2.0 and
 * a commercial license. You may choose to use this software under either
 * license.
 *
 * See the LICENSE files in the project root for full license text.
 */

// Code generated from the royaljelly std packages; DO NOT EDIT.

package transpiler

// royaljellyFunctions describes the standard functions of royaljelly's std
// packages: each parameter's Go type ("" for a type parameter), and the
// type of the result ("" for a type parameter) and whether an error follows it.
var royaljellyFunctions = map[string]stdFunction{
	"ABS":                {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"ACOS":               {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"ACOSH":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ACOS_LREAL":         {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ADD":                {pkg: "arithmetic", params: []string{""}, variadic: true, result: "", err: false},
	"ADD_DT":             {pkg: "arithmetic", params: []string{"iec.DT", "iec.TIME"}, variadic: false, result: "iec.DT", err: false},
	"ADD_TIME":           {pkg: "arithmetic", params: []string{"iec.TIME", "iec.TIME"}, variadic: false, result: "iec.TIME", err: false},
	"ADD_TOD":            {pkg: "arithmetic", params: []string{"iec.TOD", "iec.TIME"}, variadic: false, result: "iec.TOD", err: false},
	"AND":                {pkg: "bitwise", params: []string{""}, variadic: true, result: "", err: false},
	"AND_BOOL":           {pkg: "bitwise", params: []string{""}, variadic: true, result: "", err: false},
	"ASIN":               {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"ASINH":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ASIN_LREAL":         {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ATAN":               {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"ATAN2":              {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ATAN_LREAL":         {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"BITS_TO_LREAL":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.LREAL", err: false},
	"BITS_TO_REAL":       {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.REAL", err: false},
	"BOOL_TO_BYTE":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.BYTE", err: false},
	"BOOL_TO_DATE":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.DATE", err: false},
	"BOOL_TO_DINT":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.DINT", err: false},
	"BOOL_TO_DT":         {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.DT", err: false},
	"BOOL_TO_DWORD":      {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.DWORD", err: false},
	"BOOL_TO_INT":        {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.INT", err: false},
	"BOOL_TO_LINT":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.LINT", err: false},
	"BOOL_TO_LREAL":      {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.LREAL", err: false},
	"BOOL_TO_LWORD":      {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.LWORD", err: false},
	"BOOL_TO_REAL":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.REAL", err: false},
	"BOOL_TO_SINT":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.SINT", err: false},
	"BOOL_TO_STRING":     {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.STRING", err: false},
	"BOOL_TO_TIME":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.TIME", err: false},
	"BOOL_TO_TOD":        {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.TOD", err: false},
	"BOOL_TO_UDINT":      {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.UDINT", err: false},
	"BOOL_TO_UINT":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.UINT", err: false},
	"BOOL_TO_ULINT":      {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.ULINT", err: false},
	"BOOL_TO_USINT":      {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.USINT", err: false},
	"BOOL_TO_WORD":       {pkg: "conversion", params: []string{"iec.BOOL"}, variadic: false, result: "iec.WORD", err: false},
	"BYTES_TO_STRING":    {pkg: "conversion", params: []string{"[]iec.BYTE"}, variadic: false, result: "iec.STRING", err: false},
	"BYTE_BCD_TO_USINT":  {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.USINT", err: true},
	"BYTE_TO_BOOL":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.BOOL", err: false},
	"BYTE_TO_DATE":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.DATE", err: false},
	"BYTE_TO_DINT":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.DINT", err: false},
	"BYTE_TO_DT":         {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.DT", err: false},
	"BYTE_TO_DWORD":      {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.DWORD", err: false},
	"BYTE_TO_INT":        {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.INT", err: false},
	"BYTE_TO_LINT":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.LINT", err: false},
	"BYTE_TO_LREAL":      {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.LREAL", err: false},
	"BYTE_TO_LWORD":      {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.LWORD", err: false},
	"BYTE_TO_REAL":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.REAL", err: false},
	"BYTE_TO_SINT":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.SINT", err: false},
	"BYTE_TO_STRING":     {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.STRING", err: false},
	"BYTE_TO_TIME":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.TIME", err: false},
	"BYTE_TO_TOD":        {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.TOD", err: false},
	"BYTE_TO_UDINT":      {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.UDINT", err: false},
	"BYTE_TO_UINT":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.UINT", err: false},
	"BYTE_TO_ULINT":      {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.ULINT", err: false},
	"BYTE_TO_USINT":      {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.USINT", err: false},
	"BYTE_TO_WORD":       {pkg: "conversion", params: []string{"iec.BYTE"}, variadic: false, result: "iec.WORD", err: false},
	"CBRT":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"CEIL":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"CLONE":              {pkg: "strings", params: []string{"iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"COMPARE":            {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"CONCAT":             {pkg: "strings", params: []string{"iec.STRING"}, variadic: true, result: "iec.STRING", err: false},
	"CONCAT_DATE_TOD":    {pkg: "arithmetic", params: []string{"iec.DATE", "iec.TOD"}, variadic: false, result: "iec.DT", err: false},
	"CONTAINS":           {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.BOOL", err: false},
	"CONTAINSANY":        {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.BOOL", err: false},
	"CONTAINSRUNE":       {pkg: "strings", params: []string{"iec.STRING", "iec.WCHAR"}, variadic: false, result: "iec.BOOL", err: false},
	"COPYSIGN":           {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"COS":                {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"COSH":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"COS_LREAL":          {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"COUNT":              {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"DATE_TO_BYTE":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.BYTE", err: false},
	"DATE_TO_DINT":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.DINT", err: false},
	"DATE_TO_DT":         {pkg: "time", params: []string{"iec.DATE"}, variadic: false, result: "iec.DT", err: false},
	"DATE_TO_DWORD":      {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.DWORD", err: false},
	"DATE_TO_INT":        {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.INT", err: false},
	"DATE_TO_LINT":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.LINT", err: false},
	"DATE_TO_LREAL":      {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.LREAL", err: false},
	"DATE_TO_LWORD":      {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.LWORD", err: false},
	"DATE_TO_REAL":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.REAL", err: false},
	"DATE_TO_SINT":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.SINT", err: false},
	"DATE_TO_STRING":     {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.STRING", err: false},
	"DATE_TO_TIME":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.TIME", err: false},
	"DATE_TO_UDINT":      {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.UDINT", err: false},
	"DATE_TO_UINT":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.UINT", err: false},
	"DATE_TO_ULINT":      {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.ULINT", err: false},
	"DATE_TO_USINT":      {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.USINT", err: false},
	"DATE_TO_WORD":       {pkg: "conversion", params: []string{"iec.DATE"}, variadic: false, result: "iec.WORD", err: false},
	"DELETE":             {pkg: "strings", params: []string{"iec.STRING", "iec.LINT", "iec.LINT"}, variadic: false, result: "iec.STRING", err: false},
	"DIM":                {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"DINT_TO_BOOL":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.BOOL", err: false},
	"DINT_TO_BYTE":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.BYTE", err: false},
	"DINT_TO_DATE":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.DATE", err: false},
	"DINT_TO_DT":         {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.DT", err: false},
	"DINT_TO_DWORD":      {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.DWORD", err: false},
	"DINT_TO_INT":        {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.INT", err: false},
	"DINT_TO_LINT":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.LINT", err: false},
	"DINT_TO_LREAL":      {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.LREAL", err: false},
	"DINT_TO_LWORD":      {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.LWORD", err: false},
	"DINT_TO_REAL":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.REAL", err: false},
	"DINT_TO_SINT":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.SINT", err: false},
	"DINT_TO_STRING":     {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.STRING", err: false},
	"DINT_TO_TIME":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.TIME", err: false},
	"DINT_TO_TOD":        {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.TOD", err: false},
	"DINT_TO_UDINT":      {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.UDINT", err: false},
	"DINT_TO_UINT":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.UINT", err: false},
	"DINT_TO_ULINT":      {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.ULINT", err: false},
	"DINT_TO_USINT":      {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.USINT", err: false},
	"DINT_TO_WORD":       {pkg: "conversion", params: []string{"iec.DINT"}, variadic: false, result: "iec.WORD", err: false},
	"DIV":                {pkg: "arithmetic", params: []string{""}, variadic: true, result: "", err: true},
	"DIV_TIME":           {pkg: "arithmetic", params: []string{"iec.TIME", "any"}, variadic: false, result: "iec.TIME", err: true},
	"DT_TO_BYTE":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.BYTE", err: false},
	"DT_TO_DATE":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.DATE", err: false},
	"DT_TO_DINT":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.DINT", err: false},
	"DT_TO_DWORD":        {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.DWORD", err: false},
	"DT_TO_INT":          {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.INT", err: false},
	"DT_TO_LINT":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.LINT", err: false},
	"DT_TO_LREAL":        {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.LREAL", err: false},
	"DT_TO_LWORD":        {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.LWORD", err: false},
	"DT_TO_REAL":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.REAL", err: false},
	"DT_TO_SINT":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.SINT", err: false},
	"DT_TO_STRING":       {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.STRING", err: false},
	"DT_TO_TM":           {pkg: "time", params: []string{"iec.DT"}, variadic: false, result: "iec.TM", err: false},
	"DT_TO_TOD":          {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.TOD", err: false},
	"DT_TO_UDINT":        {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.UDINT", err: false},
	"DT_TO_UINT":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.UINT", err: false},
	"DT_TO_ULINT":        {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.ULINT", err: false},
	"DT_TO_USINT":        {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.USINT", err: false},
	"DT_TO_WORD":         {pkg: "conversion", params: []string{"iec.DT"}, variadic: false, result: "iec.WORD", err: false},
	"DWORD_BCD_TO_UDINT": {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.UDINT", err: true},
	"DWORD_TO_BOOL":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.BOOL", err: false},
	"DWORD_TO_BYTE":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.BYTE", err: false},
	"DWORD_TO_DATE":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.DATE", err: false},
	"DWORD_TO_DINT":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.DINT", err: false},
	"DWORD_TO_DT":        {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.DT", err: false},
	"DWORD_TO_INT":       {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.INT", err: false},
	"DWORD_TO_LINT":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.LINT", err: false},
	"DWORD_TO_LREAL":     {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.LREAL", err: false},
	"DWORD_TO_LWORD":     {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.LWORD", err: false},
	"DWORD_TO_REAL":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.REAL", err: false},
	"DWORD_TO_SINT":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.SINT", err: false},
	"DWORD_TO_STRING":    {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.STRING", err: false},
	"DWORD_TO_TIME":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.TIME", err: false},
	"DWORD_TO_TOD":       {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.TOD", err: false},
	"DWORD_TO_UDINT":     {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.UDINT", err: false},
	"DWORD_TO_UINT":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.UINT", err: false},
	"DWORD_TO_ULINT":     {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.ULINT", err: false},
	"DWORD_TO_USINT":     {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.USINT", err: false},
	"DWORD_TO_WORD":      {pkg: "conversion", params: []string{"iec.DWORD"}, variadic: false, result: "iec.WORD", err: false},
	"EQ":                 {pkg: "comparison", params: []string{""}, variadic: true, result: "iec.BOOL", err: false},
	"EQUALFOLD":          {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.BOOL", err: false},
	"ERF":                {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ERFC":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ERFCINV":            {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ERFINV":             {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"EXP":                {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"EXP2":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"EXPM1":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"EXPT":               {pkg: "numerical", params: []string{"", ""}, variadic: false, result: "", err: false},
	"EXP_LREAL":          {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"FIELDS":             {pkg: "strings", params: []string{"iec.STRING"}, variadic: false, result: "iec.STRINGS", err: false},
	"FIELDSFUNC":         {pkg: "strings", params: []string{"iec.STRING", "func"}, variadic: false, result: "iec.STRINGS", err: false},
	"FIND":               {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"FLOOR":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"FMA":                {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"GAMMA":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"GE":                 {pkg: "comparison", params: []string{""}, variadic: true, result: "iec.BOOL", err: false},
	"GT":                 {pkg: "comparison", params: []string{""}, variadic: true, result: "iec.BOOL", err: false},
	"HASPREFIX":          {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.BOOL", err: false},
	"HASSUFFIX":          {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.BOOL", err: false},
	"HYPOT":              {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ILOGB":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LINT", err: false},
	"INDEX":              {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"INDEXANY":           {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"INDEXBYTE":          {pkg: "strings", params: []string{"iec.STRING", "iec.BYTE"}, variadic: false, result: "iec.LINT", err: false},
	"INDEXFUNC":          {pkg: "strings", params: []string{"iec.STRING", "func"}, variadic: false, result: "iec.LINT", err: false},
	"INDEXRUNE":          {pkg: "strings", params: []string{"iec.STRING", "iec.WCHAR"}, variadic: false, result: "iec.LINT", err: false},
	"INF":                {pkg: "math", params: []string{"iec.LINT"}, variadic: false, result: "iec.LREAL", err: false},
	"INSERT":             {pkg: "strings", params: []string{"iec.STRING", "iec.STRING", "iec.LINT"}, variadic: false, result: "iec.STRING", err: true},
	"INT_TO_BOOL":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.BOOL", err: false},
	"INT_TO_BYTE":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.BYTE", err: false},
	"INT_TO_DATE":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.DATE", err: false},
	"INT_TO_DINT":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.DINT", err: false},
	"INT_TO_DT":          {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.DT", err: false},
	"INT_TO_DWORD":       {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.DWORD", err: false},
	"INT_TO_LINT":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.LINT", err: false},
	"INT_TO_LREAL":       {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.LREAL", err: false},
	"INT_TO_LWORD":       {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.LWORD", err: false},
	"INT_TO_REAL":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.REAL", err: false},
	"INT_TO_SINT":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.SINT", err: false},
	"INT_TO_STRING":      {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.STRING", err: false},
	"INT_TO_TIME":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.TIME", err: false},
	"INT_TO_TOD":         {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.TOD", err: false},
	"INT_TO_UDINT":       {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.UDINT", err: false},
	"INT_TO_UINT":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.UINT", err: false},
	"INT_TO_ULINT":       {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.ULINT", err: false},
	"INT_TO_USINT":       {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.USINT", err: false},
	"INT_TO_WORD":        {pkg: "conversion", params: []string{"iec.INT"}, variadic: false, result: "iec.WORD", err: false},
	"ISINF":              {pkg: "math", params: []string{"iec.LREAL", "iec.LINT"}, variadic: false, result: "iec.BOOL", err: false},
	"ISNAN":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.BOOL", err: false},
	"J0":                 {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"J1":                 {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"JN":                 {pkg: "math", params: []string{"iec.LINT", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"JOIN":               {pkg: "strings", params: []string{"iec.STRINGS", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"LASTINDEX":          {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"LASTINDEXANY":       {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"LASTINDEXBYTE":      {pkg: "strings", params: []string{"iec.STRING", "iec.BYTE"}, variadic: false, result: "iec.LINT", err: false},
	"LASTINDEXFUNC":      {pkg: "strings", params: []string{"iec.STRING", "func"}, variadic: false, result: "iec.LINT", err: false},
	"LDEXP":              {pkg: "math", params: []string{"iec.LREAL", "iec.LINT"}, variadic: false, result: "iec.LREAL", err: false},
	"LE":                 {pkg: "comparison", params: []string{""}, variadic: true, result: "iec.BOOL", err: false},
	"LEFT":               {pkg: "strings", params: []string{"iec.STRING", "iec.LINT"}, variadic: false, result: "iec.STRING", err: true},
	"LEN":                {pkg: "strings", params: []string{"iec.STRING"}, variadic: false, result: "iec.LINT", err: false},
	"LIMIT":              {pkg: "selection", params: []string{"", "", ""}, variadic: false, result: "", err: false},
	"LINT_TO_BOOL":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.BOOL", err: false},
	"LINT_TO_BYTE":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.BYTE", err: false},
	"LINT_TO_DATE":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.DATE", err: false},
	"LINT_TO_DINT":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.DINT", err: false},
	"LINT_TO_DWORD":      {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.DWORD", err: false},
	"LINT_TO_INT":        {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.INT", err: false},
	"LINT_TO_LREAL":      {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.LREAL", err: false},
	"LINT_TO_LWORD":      {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.LWORD", err: false},
	"LINT_TO_REAL":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.REAL", err: false},
	"LINT_TO_SINT":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.SINT", err: false},
	"LINT_TO_STRING":     {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.STRING", err: false},
	"LINT_TO_TIME":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.TIME", err: false},
	"LINT_TO_TOD":        {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.TOD", err: false},
	"LINT_TO_UDINT":      {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.UDINT", err: false},
	"LINT_TO_UINT":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.UINT", err: false},
	"LINT_TO_ULINT":      {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.ULINT", err: false},
	"LINT_TO_USINT":      {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.USINT", err: false},
	"LINT_TO_WORD":       {pkg: "conversion", params: []string{"iec.LINT"}, variadic: false, result: "iec.WORD", err: false},
	"LN":                 {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"LOCAL":              {pkg: "time", params: []string{"iec.TIMESPEC"}, variadic: false, result: "iec.TIMESPEC", err: false},
	"LOG":                {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"LOG10":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"LOG1P":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"LOG2":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"LOGB":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"LOG_LREAL":          {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"LREAL_TO_BITS":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.ULINT", err: false},
	"LREAL_TO_BOOL":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.BOOL", err: false},
	"LREAL_TO_BYTE":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.BYTE", err: false},
	"LREAL_TO_DATE":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.DATE", err: false},
	"LREAL_TO_DINT":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.DINT", err: false},
	"LREAL_TO_DT":        {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.DT", err: false},
	"LREAL_TO_DWORD":     {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.DWORD", err: false},
	"LREAL_TO_INT":       {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.INT", err: false},
	"LREAL_TO_LINT":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LINT", err: false},
	"LREAL_TO_LWORD":     {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LWORD", err: false},
	"LREAL_TO_REAL":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.REAL", err: false},
	"LREAL_TO_SINT":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.SINT", err: false},
	"LREAL_TO_STRING":    {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.STRING", err: false},
	"LREAL_TO_TIME":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.TIME", err: false},
	"LREAL_TO_TOD":       {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.TOD", err: false},
	"LREAL_TO_UDINT":     {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.UDINT", err: false},
	"LREAL_TO_UINT":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.UINT", err: false},
	"LREAL_TO_ULINT":     {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.ULINT", err: false},
	"LREAL_TO_USINT":     {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.USINT", err: false},
	"LREAL_TO_WORD":      {pkg: "conversion", params: []string{"iec.LREAL"}, variadic: false, result: "iec.WORD", err: false},
	"LT":                 {pkg: "comparison", params: []string{""}, variadic: true, result: "iec.BOOL", err: false},
	"LWORD_BCD_TO_ULINT": {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.ULINT", err: true},
	"LWORD_TO_BOOL":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.BOOL", err: false},
	"LWORD_TO_BYTE":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.BYTE", err: false},
	"LWORD_TO_DATE":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.DATE", err: false},
	"LWORD_TO_DINT":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.DINT", err: false},
	"LWORD_TO_DT":        {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.DT", err: false},
	"LWORD_TO_DWORD":     {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.DWORD", err: false},
	"LWORD_TO_INT":       {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.INT", err: false},
	"LWORD_TO_LINT":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.LINT", err: false},
	"LWORD_TO_LREAL":     {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.LREAL", err: false},
	"LWORD_TO_REAL":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.REAL", err: false},
	"LWORD_TO_SINT":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.SINT", err: false},
	"LWORD_TO_STRING":    {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.STRING", err: false},
	"LWORD_TO_TIME":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.TIME", err: false},
	"LWORD_TO_TOD":       {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.TOD", err: false},
	"LWORD_TO_UDINT":     {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.UDINT", err: false},
	"LWORD_TO_UINT":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.UINT", err: false},
	"LWORD_TO_ULINT":     {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.ULINT", err: false},
	"LWORD_TO_USINT":     {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.USINT", err: false},
	"LWORD_TO_WORD":      {pkg: "conversion", params: []string{"iec.LWORD"}, variadic: false, result: "iec.WORD", err: false},
	"MAP":                {pkg: "strings", params: []string{"func", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"MAX":                {pkg: "selection", params: []string{""}, variadic: true, result: "", err: true},
	"MID":                {pkg: "strings", params: []string{"iec.STRING", "iec.LINT", "iec.LINT"}, variadic: false, result: "iec.STRING", err: true},
	"MIN":                {pkg: "selection", params: []string{""}, variadic: true, result: "", err: true},
	"MOD":                {pkg: "arithmetic", params: []string{""}, variadic: true, result: "", err: true},
	"MODL":               {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"MOVE":               {pkg: "arithmetic", params: []string{""}, variadic: false, result: "", err: false},
	"MUL":                {pkg: "arithmetic", params: []string{""}, variadic: true, result: "", err: false},
	"MUL_TIME":           {pkg: "arithmetic", params: []string{"iec.TIME", "any"}, variadic: false, result: "iec.TIME", err: true},
	"MUX":                {pkg: "selection", params: []string{"", ""}, variadic: true, result: "", err: true},
	"NE":                 {pkg: "comparison", params: []string{"", ""}, variadic: false, result: "iec.BOOL", err: false},
	"NEXTAFTER":          {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"NEXTAFTER32":        {pkg: "math", params: []string{"iec.REAL", "iec.REAL"}, variadic: false, result: "iec.REAL", err: false},
	"NOT":                {pkg: "bitwise", params: []string{""}, variadic: false, result: "", err: false},
	"NOT_BOOL":           {pkg: "bitwise", params: []string{""}, variadic: false, result: "", err: false},
	"NOW":                {pkg: "time", params: []string{}, variadic: false, result: "iec.TIMESPEC", err: false},
	"OR":                 {pkg: "bitwise", params: []string{""}, variadic: true, result: "", err: false},
	"OR_BOOL":            {pkg: "bitwise", params: []string{""}, variadic: true, result: "", err: false},
	"POW":                {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"POW10":              {pkg: "math", params: []string{"iec.LINT"}, variadic: false, result: "iec.LREAL", err: true},
	"RAND":               {pkg: "math", params: []string{"any"}, variadic: false, result: "any", err: true},
	"REAL_TO_BITS":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.UDINT", err: false},
	"REAL_TO_BOOL":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.BOOL", err: false},
	"REAL_TO_BYTE":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.BYTE", err: false},
	"REAL_TO_DATE":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.DATE", err: false},
	"REAL_TO_DINT":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.DINT", err: false},
	"REAL_TO_DT":         {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.DT", err: false},
	"REAL_TO_DWORD":      {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.DWORD", err: false},
	"REAL_TO_INT":        {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.INT", err: false},
	"REAL_TO_LINT":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.LINT", err: false},
	"REAL_TO_LREAL":      {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.LREAL", err: false},
	"REAL_TO_LWORD":      {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.LWORD", err: false},
	"REAL_TO_SINT":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.SINT", err: false},
	"REAL_TO_STRING":     {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.STRING", err: false},
	"REAL_TO_TIME":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.TIME", err: false},
	"REAL_TO_TOD":        {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.TOD", err: false},
	"REAL_TO_UDINT":      {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.UDINT", err: false},
	"REAL_TO_UINT":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.UINT", err: false},
	"REAL_TO_ULINT":      {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.ULINT", err: false},
	"REAL_TO_USINT":      {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.USINT", err: false},
	"REAL_TO_WORD":       {pkg: "conversion", params: []string{"iec.REAL"}, variadic: false, result: "iec.WORD", err: false},
	"REMAINDER":          {pkg: "math", params: []string{"iec.LREAL", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"REPEAT":             {pkg: "strings", params: []string{"iec.STRING", "iec.DINT"}, variadic: false, result: "iec.STRING", err: true},
	"REPLACE":            {pkg: "strings", params: []string{"iec.STRING", "iec.STRING", "iec.LINT", "iec.LINT"}, variadic: false, result: "iec.STRING", err: true},
	"REPLACE_ALL":        {pkg: "strings", params: []string{"iec.STRING", "iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"REPLACE_STR":        {pkg: "strings", params: []string{"iec.STRING", "iec.STRING", "iec.STRING", "iec.LINT"}, variadic: false, result: "iec.STRING", err: false},
	"RIGHT":              {pkg: "strings", params: []string{"iec.STRING", "iec.LINT"}, variadic: false, result: "iec.STRING", err: true},
	"ROL":                {pkg: "bitwise", params: []string{"", "int"}, variadic: false, result: "", err: false},
	"ROR":                {pkg: "bitwise", params: []string{"", "int"}, variadic: false, result: "", err: false},
	"ROUND":              {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"ROUNTOEVEN":         {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"SEL":                {pkg: "selection", params: []string{"iec.BOOL", "", ""}, variadic: false, result: "", err: false},
	"SHL":                {pkg: "bitwise", params: []string{"", "uint"}, variadic: false, result: "", err: false},
	"SHR":                {pkg: "bitwise", params: []string{"", "uint"}, variadic: false, result: "", err: false},
	"SIGNBIT":            {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.BOOL", err: false},
	"SIN":                {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"SINH":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"SINT_TO_BOOL":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.BOOL", err: false},
	"SINT_TO_BYTE":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.BYTE", err: false},
	"SINT_TO_DATE":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.DATE", err: false},
	"SINT_TO_DINT":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.DINT", err: false},
	"SINT_TO_DT":         {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.DT", err: false},
	"SINT_TO_DWORD":      {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.DWORD", err: false},
	"SINT_TO_INT":        {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.INT", err: false},
	"SINT_TO_LINT":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.LINT", err: false},
	"SINT_TO_LREAL":      {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.LREAL", err: false},
	"SINT_TO_LWORD":      {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.LWORD", err: false},
	"SINT_TO_REAL":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.REAL", err: false},
	"SINT_TO_STRING":     {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.STRING", err: false},
	"SINT_TO_TIME":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.TIME", err: false},
	"SINT_TO_TOD":        {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.TOD", err: false},
	"SINT_TO_UDINT":      {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.UDINT", err: false},
	"SINT_TO_UINT":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.UINT", err: false},
	"SINT_TO_ULINT":      {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.ULINT", err: false},
	"SINT_TO_USINT":      {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.USINT", err: false},
	"SINT_TO_WORD":       {pkg: "conversion", params: []string{"iec.SINT"}, variadic: false, result: "iec.WORD", err: false},
	"SIN_LREAL":          {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"SPLIT":              {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRINGS", err: false},
	"SPLITAFTER":         {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRINGS", err: false},
	"SPLITAFTERN":        {pkg: "strings", params: []string{"iec.STRING", "iec.STRING", "iec.LINT"}, variadic: false, result: "iec.STRINGS", err: false},
	"SPLITN":             {pkg: "strings", params: []string{"iec.STRING", "iec.STRING", "iec.LINT"}, variadic: false, result: "iec.STRINGS", err: false},
	"SQRT":               {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"SQRT_LREAL":         {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"STRING_TO_DATE":     {pkg: "time", params: []string{"iec.STRING"}, variadic: false, result: "iec.DATE", err: true},
	"STRING_TO_DT":       {pkg: "time", params: []string{"iec.STRING"}, variadic: false, result: "iec.DT", err: true},
	"STRING_TO_TIME":     {pkg: "time", params: []string{"iec.STRING"}, variadic: false, result: "iec.TIME", err: true},
	"STRING_TO_TOD":      {pkg: "time", params: []string{"iec.STRING"}, variadic: false, result: "iec.TOD", err: true},
	"SUB":                {pkg: "arithmetic", params: []string{""}, variadic: true, result: "", err: false},
	"SUB_DATE":           {pkg: "arithmetic", params: []string{"iec.DATE", "iec.DATE"}, variadic: false, result: "iec.TIME", err: false},
	"SUB_DT_DT":          {pkg: "arithmetic", params: []string{"iec.DT", "iec.DT"}, variadic: false, result: "iec.TIME", err: false},
	"SUB_DT_TIME":        {pkg: "arithmetic", params: []string{"iec.DT", "iec.TIME"}, variadic: false, result: "iec.DT", err: false},
	"SUB_TIME":           {pkg: "arithmetic", params: []string{"iec.TIME", "iec.TIME"}, variadic: false, result: "iec.TIME", err: false},
	"SUB_TOD_TIME":       {pkg: "arithmetic", params: []string{"iec.TOD", "iec.TIME"}, variadic: false, result: "iec.TOD", err: false},
	"SUB_TOD_TOD":        {pkg: "arithmetic", params: []string{"iec.TOD", "iec.TOD"}, variadic: false, result: "iec.TIME", err: false},
	"SUM":                {pkg: "numerical", params: []string{"*ast.MapType"}, variadic: false, result: "", err: false},
	"SUMLINT":            {pkg: "numerical", params: []string{"*ast.MapType"}, variadic: false, result: "iec.LINT", err: false},
	"SUMLREAL":           {pkg: "numerical", params: []string{"*ast.MapType"}, variadic: false, result: "iec.LREAL", err: false},
	"SUMREAL":            {pkg: "numerical", params: []string{"*ast.MapType"}, variadic: false, result: "iec.REAL", err: false},
	"TAN":                {pkg: "numerical", params: []string{""}, variadic: false, result: "", err: false},
	"TANH":               {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"TAN_LREAL":          {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"TIME_TO_BYTE":       {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.BYTE", err: false},
	"TIME_TO_DINT":       {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.DINT", err: false},
	"TIME_TO_DWORD":      {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.DWORD", err: false},
	"TIME_TO_INT":        {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.INT", err: false},
	"TIME_TO_LINT":       {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.LINT", err: false},
	"TIME_TO_LREAL":      {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.LREAL", err: false},
	"TIME_TO_LWORD":      {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.LWORD", err: false},
	"TIME_TO_REAL":       {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.REAL", err: false},
	"TIME_TO_SINT":       {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.SINT", err: false},
	"TIME_TO_STRING":     {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.STRING", err: false},
	"TIME_TO_UDINT":      {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.UDINT", err: false},
	"TIME_TO_UINT":       {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.UINT", err: false},
	"TIME_TO_ULINT":      {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.ULINT", err: false},
	"TIME_TO_USINT":      {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.USINT", err: false},
	"TIME_TO_WORD":       {pkg: "conversion", params: []string{"iec.TIME"}, variadic: false, result: "iec.WORD", err: false},
	"TM_TO_DT":           {pkg: "time", params: []string{"iec.TM"}, variadic: false, result: "iec.DT", err: false},
	"TOD_TO_BYTE":        {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.BYTE", err: false},
	"TOD_TO_DINT":        {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.DINT", err: false},
	"TOD_TO_DT":          {pkg: "time", params: []string{"iec.TOD"}, variadic: false, result: "iec.DT", err: false},
	"TOD_TO_DWORD":       {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.DWORD", err: false},
	"TOD_TO_INT":         {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.INT", err: false},
	"TOD_TO_LINT":        {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.LINT", err: false},
	"TOD_TO_LREAL":       {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.LREAL", err: false},
	"TOD_TO_LWORD":       {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.LWORD", err: false},
	"TOD_TO_REAL":        {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.REAL", err: false},
	"TOD_TO_SINT":        {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.SINT", err: false},
	"TOD_TO_STRING":      {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.STRING", err: false},
	"TOD_TO_UDINT":       {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.UDINT", err: false},
	"TOD_TO_UINT":        {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.UINT", err: false},
	"TOD_TO_ULINT":       {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.ULINT", err: false},
	"TOD_TO_USINT":       {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.USINT", err: false},
	"TOD_TO_WORD":        {pkg: "conversion", params: []string{"iec.TOD"}, variadic: false, result: "iec.WORD", err: false},
	"TOLOWER":            {pkg: "strings", params: []string{"iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TOTITLE":            {pkg: "strings", params: []string{"iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TOUPPER":            {pkg: "strings", params: []string{"iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TOVALIDUTF8":        {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TRIM":               {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMFUNC":           {pkg: "strings", params: []string{"iec.STRING", "func"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMLEFT":           {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMLEFTFUNC":       {pkg: "strings", params: []string{"iec.STRING", "func"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMPREFIX":         {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMRIGHT":          {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMRIGHTFUNC":      {pkg: "strings", params: []string{"iec.STRING", "func"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMSPACE":          {pkg: "strings", params: []string{"iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TRIMSUFFIX":         {pkg: "strings", params: []string{"iec.STRING", "iec.STRING"}, variadic: false, result: "iec.STRING", err: false},
	"TRUNC":              {pkg: "numerical", params: []string{""}, variadic: false, result: "iec.DINT", err: false},
	"TRUNC_LREAL":        {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"UDINT_TO_BCD_DWORD": {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.DWORD", err: true},
	"UDINT_TO_BOOL":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.BOOL", err: false},
	"UDINT_TO_BYTE":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.BYTE", err: false},
	"UDINT_TO_DATE":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.DATE", err: false},
	"UDINT_TO_DINT":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.DINT", err: false},
	"UDINT_TO_DT":        {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.DT", err: false},
	"UDINT_TO_DWORD":     {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.DWORD", err: false},
	"UDINT_TO_INT":       {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.INT", err: false},
	"UDINT_TO_LINT":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.LINT", err: false},
	"UDINT_TO_LREAL":     {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.LREAL", err: false},
	"UDINT_TO_LWORD":     {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.LWORD", err: false},
	"UDINT_TO_REAL":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.REAL", err: false},
	"UDINT_TO_SINT":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.SINT", err: false},
	"UDINT_TO_STRING":    {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.STRING", err: false},
	"UDINT_TO_TIME":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.TIME", err: false},
	"UDINT_TO_TOD":       {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.TOD", err: false},
	"UDINT_TO_UINT":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.UINT", err: false},
	"UDINT_TO_ULINT":     {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.ULINT", err: false},
	"UDINT_TO_USINT":     {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.USINT", err: false},
	"UDINT_TO_WORD":      {pkg: "conversion", params: []string{"iec.UDINT"}, variadic: false, result: "iec.WORD", err: false},
	"UINT_TO_BCD_WORD":   {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.WORD", err: true},
	"UINT_TO_BOOL":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.BOOL", err: false},
	"UINT_TO_BYTE":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.BYTE", err: false},
	"UINT_TO_DATE":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.DATE", err: false},
	"UINT_TO_DINT":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.DINT", err: false},
	"UINT_TO_DT":         {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.DT", err: false},
	"UINT_TO_DWORD":      {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.DWORD", err: false},
	"UINT_TO_INT":        {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.INT", err: false},
	"UINT_TO_LINT":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.LINT", err: false},
	"UINT_TO_LREAL":      {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.LREAL", err: false},
	"UINT_TO_LWORD":      {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.LWORD", err: false},
	"UINT_TO_REAL":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.REAL", err: false},
	"UINT_TO_SINT":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.SINT", err: false},
	"UINT_TO_STRING":     {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.STRING", err: false},
	"UINT_TO_TIME":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.TIME", err: false},
	"UINT_TO_TOD":        {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.TOD", err: false},
	"UINT_TO_UDINT":      {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.UDINT", err: false},
	"UINT_TO_ULINT":      {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.ULINT", err: false},
	"UINT_TO_USINT":      {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.USINT", err: false},
	"UINT_TO_WORD":       {pkg: "conversion", params: []string{"iec.UINT"}, variadic: false, result: "iec.WORD", err: false},
	"ULINT_TO_BCD_LWORD": {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.LWORD", err: true},
	"ULINT_TO_BOOL":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.BOOL", err: false},
	"ULINT_TO_BYTE":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.BYTE", err: false},
	"ULINT_TO_DATE":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.DATE", err: false},
	"ULINT_TO_DINT":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.DINT", err: false},
	"ULINT_TO_DT":        {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.DT", err: false},
	"ULINT_TO_DWORD":     {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.DWORD", err: false},
	"ULINT_TO_INT":       {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.INT", err: false},
	"ULINT_TO_LINT":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.LINT", err: false},
	"ULINT_TO_LREAL":     {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.LREAL", err: false},
	"ULINT_TO_LWORD":     {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.LWORD", err: false},
	"ULINT_TO_REAL":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.REAL", err: false},
	"ULINT_TO_SINT":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.SINT", err: false},
	"ULINT_TO_STRING":    {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.STRING", err: false},
	"ULINT_TO_TIME":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.TIME", err: false},
	"ULINT_TO_TOD":       {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.TOD", err: false},
	"ULINT_TO_UDINT":     {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.UDINT", err: false},
	"ULINT_TO_UINT":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.UINT", err: false},
	"ULINT_TO_USINT":     {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.USINT", err: false},
	"ULINT_TO_WORD":      {pkg: "conversion", params: []string{"iec.ULINT"}, variadic: false, result: "iec.WORD", err: false},
	"USINT_TO_BCD_BYTE":  {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.BYTE", err: true},
	"USINT_TO_BOOL":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.BOOL", err: false},
	"USINT_TO_BYTE":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.BYTE", err: false},
	"USINT_TO_DATE":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.DATE", err: false},
	"USINT_TO_DINT":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.DINT", err: false},
	"USINT_TO_DT":        {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.DT", err: false},
	"USINT_TO_DWORD":     {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.DWORD", err: false},
	"USINT_TO_INT":       {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.INT", err: false},
	"USINT_TO_LINT":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.LINT", err: false},
	"USINT_TO_LREAL":     {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.LREAL", err: false},
	"USINT_TO_LWORD":     {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.LWORD", err: false},
	"USINT_TO_REAL":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.REAL", err: false},
	"USINT_TO_SINT":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.SINT", err: false},
	"USINT_TO_STRING":    {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.STRING", err: false},
	"USINT_TO_TIME":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.TIME", err: false},
	"USINT_TO_TOD":       {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.TOD", err: false},
	"USINT_TO_UDINT":     {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.UDINT", err: false},
	"USINT_TO_UINT":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.UINT", err: false},
	"USINT_TO_ULINT":     {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.ULINT", err: false},
	"USINT_TO_WORD":      {pkg: "conversion", params: []string{"iec.USINT"}, variadic: false, result: "iec.WORD", err: false},
	"UTC":                {pkg: "time", params: []string{"iec.TIMESPEC"}, variadic: false, result: "iec.TIMESPEC", err: false},
	"WORD_BCD_TO_UINT":   {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.UINT", err: true},
	"WORD_TO_BOOL":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.BOOL", err: false},
	"WORD_TO_BYTE":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.BYTE", err: false},
	"WORD_TO_DATE":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.DATE", err: false},
	"WORD_TO_DINT":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.DINT", err: false},
	"WORD_TO_DT":         {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.DT", err: false},
	"WORD_TO_DWORD":      {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.DWORD", err: false},
	"WORD_TO_INT":        {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.INT", err: false},
	"WORD_TO_LINT":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.LINT", err: false},
	"WORD_TO_LREAL":      {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.LREAL", err: false},
	"WORD_TO_LWORD":      {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.LWORD", err: false},
	"WORD_TO_REAL":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.REAL", err: false},
	"WORD_TO_SINT":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.SINT", err: false},
	"WORD_TO_STRING":     {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.STRING", err: false},
	"WORD_TO_TIME":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.TIME", err: false},
	"WORD_TO_TOD":        {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.TOD", err: false},
	"WORD_TO_UDINT":      {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.UDINT", err: false},
	"WORD_TO_UINT":       {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.UINT", err: false},
	"WORD_TO_ULINT":      {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.ULINT", err: false},
	"WORD_TO_USINT":      {pkg: "conversion", params: []string{"iec.WORD"}, variadic: false, result: "iec.USINT", err: false},
	"XOR":                {pkg: "bitwise", params: []string{""}, variadic: true, result: "", err: false},
	"XOR_BOOL":           {pkg: "bitwise", params: []string{""}, variadic: true, result: "", err: false},
	"Y0":                 {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"Y1":                 {pkg: "math", params: []string{"iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
	"YN":                 {pkg: "math", params: []string{"iec.LINT", "iec.LREAL"}, variadic: false, result: "iec.LREAL", err: false},
}
